### ISSUE TITLE
Update Roller in FireFox & Chrome Webstore

### ISSUE THREAD

**Issue by Bamajon1974** [ubermanu/roller#3]
Good morning. Thank you for forking and updating the AutoScroll Extension. Could you please submit the latest version of Roller to the FireFox and Chrome addon/extension stores? The stores still only show the initial release. 

Thanks!

**Comment by ubermanu** [comment]
I submitted 1.2.0 to both extension stores, I'll keep you updated once it has passed the reviews

**Comment by ubermanu** [comment]
Here you go!
